# Use an official Ruby runtime as a parent image
FROM ruby:3.3.0

# Set environment variables
ENV RAILS_ENV=development
ENV RACK_ENV=development

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client nano libvips

# Set the working directory
WORKDIR /rails

# Create a non-root user matching the local UID/GID
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID rails && useradd -m -u $UID -g $GID -s /bin/bash -g rails rails

# Change ownership to the newly created user
RUN chown -R rails:rails /rails

# Switch to the non-root user
USER rails

# Copy the Gemfile and Gemfile.lock
COPY --chown=rails:rails Gemfile Gemfile.lock /rails/

# Install the gem dependencies
RUN bundle install

# Copy the rest of the application code
COPY --chown=rails:rails . /rails

# Ensure writable directories
RUN mkdir -p /rails/tmp /rails/log /rails/storage && \
    chown -R rails:rails /rails/tmp /rails/log /rails/storage

# Expose port 3000
EXPOSE 3000

# Default command
CMD ["./bin/dev"]