services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db